import { test, expect } from '@playwright/test'

const API = 'http://localhost:8001'
const created: number[] = []

test.afterEach(async ({ request }) => {
  for (const id of created.splice(0)) await request.delete(`${API}/api/meetings/${id}`)
})

test('dashboard shows seeded upcoming and recent meetings and real profile', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Alex Morgan', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Recent meetings' })).toBeVisible()
  await expect(page.getByText('User Research Sync', { exact: true })).toBeVisible()
  await expect(page.getByText('Weekly Team Sync', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Profile', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('alex.morgan@example.com')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true })
  await page.getByRole('link', { name: /User Research Sync/ }).click()
  await expect(page.getByRole('button', { name: 'Details for User Research Sync' })).toHaveAttribute('aria-expanded', 'true')
})

test('schedule, edit without losing date/time, clear description, and delete', async ({ page, request }) => {
  await page.goto('/meetings/schedule')
  const start = new Date(Date.now() + 3 * 86_400_000)
  const date = `${start.getFullYear()}-${String(start.getMonth() + 1).padStart(2, '0')}-${String(start.getDate()).padStart(2, '0')}`
  await page.getByRole('textbox', { name: 'Topic', exact: true }).fill('Browser regression meeting')
  await page.getByRole('button', { name: 'Add Description', exact: true }).click()
  await page.getByRole('textbox', { name: 'Description', exact: true }).fill('Original description')
  await page.getByLabel('Meeting date', { exact: true }).fill(date)
  await page.getByLabel('Meeting time', { exact: true }).fill('02:35')
  await page.getByLabel('AM or PM', { exact: true }).selectOption('PM')
  await page.getByLabel('Duration hours', { exact: true }).selectOption('1')
  await page.getByLabel('Duration minutes', { exact: true }).selectOption('0')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page).toHaveURL(/\/meetings$/)
  const meetings = await (await request.get(`${API}/api/meetings/?type=upcoming`)).json()
  const m = meetings.find((meeting: { title: string }) => meeting.title === 'Browser regression meeting')
  expect(m).toBeTruthy(); created.push(m.id)
  expect(new Date(m.start_time).getTime()).toBe(new Date(`${date}T14:35:00`).getTime())
  const row = page.getByRole('button', { name: 'Details for Browser regression meeting' })
  await row.hover()
  await row.getByRole('button', { name: 'Edit', exact: true }).click()
  await expect(page.getByLabel('Meeting date', { exact: true })).toHaveValue(date)
  await expect(page.getByLabel('Meeting time', { exact: true })).toHaveValue('02:35')
  await expect(page.getByLabel('AM or PM', { exact: true })).toHaveValue('PM')
  await page.getByRole('textbox', { name: 'Description', exact: true }).fill('')
  await page.getByRole('button', { name: 'Update', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const edited = await (await request.get(`${API}/api/meetings/${m.id}`)).json()
  expect(edited.start_time).toBe(m.start_time)
  expect(edited.description).toBe('')
  await row.hover()
  page.once('dialog', (dialog) => dialog.accept())
  await row.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(row).toHaveCount(0)
})

test('instant meeting generates ID and invite link, enters room, and preserves guest name', async ({ page, context, request }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'New Meeting', exact: true }).click()
  await expect(page).toHaveURL(/\/room\/\d{11}$/)
  const mid = page.url().split('/').pop()!
  const m = await (await request.post(`${API}/api/meetings/validate`, { data: { meeting_input: mid } })).json()
  created.push(m.id)
  await expect(page.getByRole('button', { name: 'Use microphone and camera', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Use microphone and camera', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Participants', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'More', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText(`/join?mid=${mid}`)
  await page.getByRole('button', { name: 'Copy URL', exact: true }).click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(`http://localhost:3001/join?mid=${mid}`)
  await page.keyboard.press('Escape')
  await expect.poll(() => page.locator('video').evaluate((video: HTMLVideoElement) => Boolean(video.srcObject))).toBeTruthy()
  await page.getByRole('button', { name: 'Stop Video', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Start Video', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Start Video', exact: true }).click()
  await expect.poll(() => page.locator('video').evaluate((video: HTMLVideoElement) => Boolean(video.srcObject))).toBeTruthy()

  const guest = await context.newPage()
  await guest.goto(`/join?mid=${mid}`)
  await expect(guest.getByRole('textbox', { name: 'Meeting ID or invite link' })).toHaveValue(mid)
  await guest.getByRole('button', { name: 'Join', exact: true }).click()
  await guest.getByRole('button', { name: 'Join from your browser', exact: true }).click()
  await guest.getByRole('textbox', { name: 'Your Name' }).fill('Browser Guest')
  await guest.getByRole('button', { name: 'Join Meeting', exact: true }).click()
  await expect(guest).toHaveURL(/guest=1/)
  await guest.getByRole('button', { name: 'Continue without microphone and camera', exact: true }).click()
  await expect(guest.getByText('Browser Guest (me)', { exact: true })).toBeVisible()
  const participants = await (await request.get(`${API}/api/meetings/${m.id}/participants/`)).json()
  expect(participants.filter((p: { display_name: string }) => p.display_name === 'Browser Guest')).toHaveLength(1)
  await page.getByRole('button', { name: 'End', exact: true }).click()
  await page.getByRole('button', { name: 'End Meeting for All', exact: true }).click()
  await expect(page).toHaveURL(/\/meetings$/)
  expect((await (await request.get(`${API}/api/meetings/${m.id}`)).json()).status).toBe('ended')
  expect(errors).toEqual([])
  await guest.close()
})

test('join accepts a full invite link and validates before asking for a name', async ({ page, request }) => {
  const m = await (await request.post(`${API}/api/meetings/instant`)).json()
  created.push(m.id)
  await page.goto('/join')
  await page.getByRole('textbox', { name: 'Meeting ID or invite link' }).fill(m.invite_link)
  await page.getByRole('button', { name: 'Join', exact: true }).click()
  await page.getByRole('button', { name: 'Join from your browser', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Your Name' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Your Name' }).fill('Invite Link Guest')
  await page.getByRole('button', { name: 'Join Meeting', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/room/${m.meeting_id}\\?guest=1$`))
  await page.getByRole('button', { name: 'Continue without microphone and camera', exact: true }).click()
  await expect(page.getByText('Invite Link Guest (me)', { exact: true })).toBeVisible()
})

test('joining can retry a temporary API failure without duplicate participants', async ({ page, request }) => {
  const m = await (await request.post(`${API}/api/meetings/instant`)).json()
  created.push(m.id)
  await page.goto(`/join?mid=${m.meeting_id}`)
  await page.getByRole('button', { name: 'Join', exact: true }).click()
  await page.getByRole('button', { name: 'Join from your browser', exact: true }).click()
  await page.getByRole('textbox', { name: 'Your Name' }).fill('Retry Guest')
  await page.getByRole('button', { name: 'Join Meeting', exact: true }).click()
  let failed = false
  await page.route('**/api/meetings/*/participants/', async (route) => {
    if (route.request().method() === 'GET' && !failed) {
      failed = true
      await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Temporary server error' }) })
    } else await route.continue()
  })
  await page.getByRole('button', { name: 'Continue without microphone and camera', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Temporary server error' })).toBeVisible()
  await page.getByRole('button', { name: 'Continue without microphone and camera', exact: true }).click()
  await expect(page.getByText('Retry Guest (me)', { exact: true })).toBeVisible()
  const participants = await (await request.get(`${API}/api/meetings/${m.id}/participants/`)).json()
  expect(participants.filter((p: { display_name: string }) => p.display_name === 'Retry Guest')).toHaveLength(1)
})

test('mobile dashboard, join, schedule and room remain within viewport', async ({ page, request }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  for (const route of ['/', '/meetings', '/join', '/meetings/schedule']) {
    await page.goto(route)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  }
  await page.goto('/')
  await page.getByRole('button', { name: 'Toggle menu' }).click()
  await page.getByRole('link', { name: 'Meetings', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Meetings', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/meetings-mobile.png', fullPage: true })
  const m = await (await request.post(`${API}/api/meetings/instant`)).json()
  created.push(m.id)
  await page.goto(`/room/${m.meeting_id}`)
  await page.getByRole('button', { name: 'Use microphone and camera', exact: true }).click()
  await page.getByRole('button', { name: 'Participants', exact: true }).click()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: 'test-results/room-mobile.png', fullPage: true })
})

test('invalid meeting is explained and past meetings cannot be started', async ({ page }) => {
  await page.goto('/join')
  await page.getByRole('textbox', { name: 'Meeting ID or invite link' }).fill('not-a-meeting')
  await page.getByRole('button', { name: 'Join', exact: true }).click()
  await expect(page.getByText('Could not parse a meeting ID from the input.')).toBeVisible()
  await page.goto('/meetings')
  await page.getByRole('button', { name: 'Previous', exact: true }).click()
  const row = page.getByRole('button', { name: 'Details for User Research Sync' })
  await row.hover()
  await expect(row.getByRole('button', { name: 'Start', exact: true })).toBeDisabled()
  await expect(row.getByRole('button', { name: 'Edit', exact: true })).toBeDisabled()
})

test('date range filters stored meetings and Escape closes the calendar', async ({ page, request }) => {
  const start = new Date(Date.now() + 10 * 86_400_000)
  const m = await (await request.post(`${API}/api/meetings/`, { data: {title:'Date range regression', start_time:start.toISOString(), duration_minutes:40, time_zone:'UTC'} })).json()
  expect(m.id).toBeTruthy(); created.push(m.id)
  await page.goto('/meetings')
  await expect(page.getByRole('button', {name:'Details for Date range regression'})).toBeVisible()
  await page.getByRole('button', {name:'Choose meeting date range'}).click()
  await expect(page.getByRole('dialog', {name:'Meeting date range'})).toBeVisible()
  const from = new Date(start); from.setDate(from.getDate() + 1)
  const date = `${from.getFullYear()}-${String(from.getMonth() + 1).padStart(2,'0')}-${String(from.getDate()).padStart(2,'0')}`
  await page.getByLabel('From date', {exact:true}).fill(date)
  await expect(page.getByRole('button', {name:'Details for Date range regression'})).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', {name:'Meeting date range'})).toHaveCount(0)
})

test('editing a start time by one minute preserves the change when stored seconds are present', async ({ page, request }) => {
  const start = new Date(Date.now() + 3 * 86_400_000)
  start.setHours(14, 35, 59, 0)
  const m = await (await request.post(`${API}/api/meetings/`, {data: {
    title:'Minute boundary regression', start_time:start.toISOString(), duration_minutes:40, time_zone:'UTC',
  }})).json()
  expect(m.id).toBeTruthy(); created.push(m.id)
  await page.goto(`/meetings?selected=${m.id}`)
  const row = page.getByRole('button', {name:'Details for Minute boundary regression'})
  await row.hover()
  await row.getByRole('button', {name:'Edit', exact:true}).click()
  await page.getByLabel('Meeting time', {exact:true}).fill('02:36')
  await page.getByRole('button', {name:'Update', exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const edited = await (await request.get(`${API}/api/meetings/${m.id}`)).json()
  start.setHours(14, 36, 0, 0)
  expect(new Date(edited.start_time).getTime()).toBe(start.getTime())
})
